### ISSUE TITLE
Add sort bar

### ISSUE THREAD

**Issue by dtlemon** [jncraton/course-search#109]
Comment what kind of selector you need and a brief description for what it will be sorting by

**Comment by jepoorbaugh** [comment]
```html
<label for="department">Select a department to filter by:</label>
<select name="department" id="dept-filter"></select>
```
Selectbox / Combobox / Dropdown Box for choosing a department to filter by. Options are dynamically added.

**Comment by Peyton3995** [comment]
I need a DropDown box, that is what it is called. 
`<select name="startTimes" id="startTimes">
    <option value="07:00:00">07:00:00</option>
    <option value="08:00:00">08:00:00</option>
    <option value="08:30:00">08:30:00</option>
    <option value="09:00:00">09:00:00</option>
    <option value="09:30:00">09:30:00</option>
    <option value="10:00:00">10:00:00</option>
    <option value="11:00:00">11:00:00</option>
    <option value="12:00:00">12:00:00</option>
    <option value="13:00:00">13:00:00</option>
    <option value="14:00:00">14:00:00</option>
    <option value="14:30:00">14:30:00</option>
    <option value="15:00:00">15:00:00</option>
    <option value="16:00:00">16:00:00</option>
    <option value="16:30:00">16:30:00</option>
    <option value="17:00:00">17:00:00</option>
    <option value="17:30:00">17:30:00</option>
    <option value="18:00:00">18:00:00</option>
    <option value="18:30:00">18:30:00</option>
    <option value="19:00:00">19:00:00</option>
    <option value="19:30:00">19:30:00</option>
  </select>`

**Comment by Peyton3995** [comment]
> I need a DropDown box, that is what it is called.
> 
> > <option value="07:00:00">07:00:00</option>
> > <option value="08:00:00">08:00:00</option>
> > <option value="08:30:00">08:30:00</option>
> > <option value="09:00:00">09:00:00</option>
> > <option value="09:30:00">09:30:00</option>
> > <option value="10:00:00">10:00:00</option>
> > <option value="11:00:00">11:00:00</option>
> > <option value="12:00:00">12:00:00</option>
> > <option value="13:00:00">13:00:00</option>
> > <option value="14:00:00">14:00:00</option>
> > <option value="14:30:00">14:30:00</option>
> > <option value="15:00:00">15:00:00</option>
> > <option value="16:00:00">16:00:00</option>
> > <option value="16:30:00">16:30:00</option>
> > <option value="17:00:00">17:00:00</option>
> > <option value="17:30:00">17:30:00</option>
> > <option value="18:00:00">18:00:00</option>
> > <option value="18:30:00">18:30:00</option>
> > <option value="19:00:00">19:00:00</option>
> > <option value="19:30:00">19:30:00</option>

idk how to format this

**Comment by Jxboss911** [comment]
<label for="row-colors">Toggle alternating row colors:</label>
<input type="checkbox" id="row-colors-toggle" />

Checkbox for toggling alternating row colors in the course table. When checked, it applies alternating background colors to odd and even rows. When unchecked, it removes the background colors.

**Comment by AndrewG2026** [comment]
I just need a button for sorting by credits

**Comment by Jxboss911** [comment]
I need a checkbox for toggling alternating row colors in the course table.

**Comment by owenmock22** [comment]
I also just need a button.  Mine is for sorting by enrollment

**Comment by dtlemon** [comment]
> I need a checkbox for toggling alternating row colors in the course table.

I think this should just be applied always, unless others disagree
